#############################################################################
# Makefile for building: PromengTest2
# Generated by qmake (2.01a) (Qt 4.8.2) on: Wed Jul 31 17:18:16 2013
# Project:  PromengTest2.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile PromengTest2.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_SQL_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtSql -I/usr/include/qt4 -I/usr/local/qwt-6.1.0/src -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu /usr/local/qwt-6.1.0/lib/libqwt.so.6 -lQtSql -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		PromengDialog.cpp \
		bitmapworker.cpp \
		db_VisualParam.cpp \
		dbconn.cpp \
		db_signal.cpp \
		CheckpointMessages.cpp \
		CheckPointProperties.cpp \
		db_CheckPointProperties.cpp \
		vec_signal.cpp \
		db_VideoFrame.cpp \
		VideoFrame.cpp \
		VisualParam.cpp \
		LoginPassword.cpp \
		DbLoginPasswords.cpp \
		LoginDialog.cpp \
		ModelLoginPassword.cpp \
		TableEditDialog.cpp \
		ModelVisualParam.cpp \
		CheckPointEditDialog.cpp \
		CheckpointPropDialog.cpp \
		plot.cpp \
		Signal.cpp \
		ModelArchivSignal.cpp \
		DelegatArchivSignal.cpp moc_mainwindow.cpp \
		moc_PromengDialog.cpp \
		moc_bitmapworker.cpp \
		moc_db_signal.cpp \
		moc_LoginDialog.cpp \
		moc_ModelLoginPassword.cpp \
		moc_TableEditDialog.cpp \
		moc_ModelVisualParam.cpp \
		moc_CheckPointEditDialog.cpp \
		moc_CheckpointPropDialog.cpp \
		moc_plot.cpp \
		moc_ModelArchivSignal.cpp \
		moc_DelegatArchivSignal.cpp \
		qrc_application.cpp
OBJECTS       = main.o \
		mainwindow.o \
		PromengDialog.o \
		bitmapworker.o \
		db_VisualParam.o \
		dbconn.o \
		db_signal.o \
		CheckpointMessages.o \
		CheckPointProperties.o \
		db_CheckPointProperties.o \
		vec_signal.o \
		db_VideoFrame.o \
		VideoFrame.o \
		VisualParam.o \
		LoginPassword.o \
		DbLoginPasswords.o \
		LoginDialog.o \
		ModelLoginPassword.o \
		TableEditDialog.o \
		ModelVisualParam.o \
		CheckPointEditDialog.o \
		CheckpointPropDialog.o \
		plot.o \
		Signal.o \
		ModelArchivSignal.o \
		DelegatArchivSignal.o \
		moc_mainwindow.o \
		moc_PromengDialog.o \
		moc_bitmapworker.o \
		moc_db_signal.o \
		moc_LoginDialog.o \
		moc_ModelLoginPassword.o \
		moc_TableEditDialog.o \
		moc_ModelVisualParam.o \
		moc_CheckPointEditDialog.o \
		moc_CheckpointPropDialog.o \
		moc_plot.o \
		moc_ModelArchivSignal.o \
		moc_DelegatArchivSignal.o \
		qrc_application.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/declarative_debug.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		PromengTest2.pro
QMAKE_TARGET  = PromengTest2
DESTDIR       = 
TARGET        = PromengTest2

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9]\+\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: PromengTest2.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/declarative_debug.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/x86_64-linux-gnu/libQtSql.prl \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile PromengTest2.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/declarative_debug.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/x86_64-linux-gnu/libQtSql.prl:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile PromengTest2.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/PromengTest21.0.0 || $(MKDIR) .tmp/PromengTest21.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/PromengTest21.0.0/ && $(COPY_FILE) --parents mainwindow.h PromengDialog.h bitmapworker.h db_VisualParam.h dbconn.h AllHeaders.h db_signal.h CheckpointMessages.h db_CheckPointProperties.h CheckPointProperties.h vec_signal.h db_VideoFrame.h VideoFrame.h VisualParam.h LoginPassword.h DbLoginPasswords.h LoginDialog.h ModelLoginPassword.h TableEditDialog.h ModelVisualParam.h CheckPointEditDialog.h CheckpointPropDialog.h plot.h Signal.h ModelArchivSignal.h DelegatArchivSignal.h .tmp/PromengTest21.0.0/ && $(COPY_FILE) --parents application.qrc .tmp/PromengTest21.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp PromengDialog.cpp bitmapworker.cpp db_VisualParam.cpp dbconn.cpp db_signal.cpp CheckpointMessages.cpp CheckPointProperties.cpp db_CheckPointProperties.cpp vec_signal.cpp db_VideoFrame.cpp VideoFrame.cpp VisualParam.cpp LoginPassword.cpp DbLoginPasswords.cpp LoginDialog.cpp ModelLoginPassword.cpp TableEditDialog.cpp ModelVisualParam.cpp CheckPointEditDialog.cpp CheckpointPropDialog.cpp plot.cpp Signal.cpp ModelArchivSignal.cpp DelegatArchivSignal.cpp .tmp/PromengTest21.0.0/ && (cd `dirname .tmp/PromengTest21.0.0` && $(TAR) PromengTest21.0.0.tar PromengTest21.0.0 && $(COMPRESS) PromengTest21.0.0.tar) && $(MOVE) `dirname .tmp/PromengTest21.0.0`/PromengTest21.0.0.tar.gz . && $(DEL_FILE) -r .tmp/PromengTest21.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_PromengDialog.cpp moc_bitmapworker.cpp moc_db_signal.cpp moc_LoginDialog.cpp moc_ModelLoginPassword.cpp moc_TableEditDialog.cpp moc_ModelVisualParam.cpp moc_CheckPointEditDialog.cpp moc_CheckpointPropDialog.cpp moc_plot.cpp moc_ModelArchivSignal.cpp moc_DelegatArchivSignal.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_PromengDialog.cpp moc_bitmapworker.cpp moc_db_signal.cpp moc_LoginDialog.cpp moc_ModelLoginPassword.cpp moc_TableEditDialog.cpp moc_ModelVisualParam.cpp moc_CheckPointEditDialog.cpp moc_CheckpointPropDialog.cpp moc_plot.cpp moc_ModelArchivSignal.cpp moc_DelegatArchivSignal.cpp
moc_mainwindow.cpp: PromengDialog.h \
		AllHeaders.h \
		dbconn.h \
		db_VisualParam.h \
		VisualParam.h \
		Signal.h \
		db_signal.h \
		vec_signal.h \
		CheckPointProperties.h \
		db_CheckPointProperties.h \
		CheckpointPropDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_zoomer.h \
		/usr/local/qwt-6.1.0/src/qwt_global.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_text.h \
		/usr/local/qwt-6.1.0/src/qwt_event_pattern.h \
		plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_date.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_div.h \
		/usr/local/qwt-6.1.0/src/qwt_interval.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_dict.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_item.h \
		/usr/local/qwt-6.1.0/src/qwt_legend_data.h \
		/usr/local/qwt-6.1.0/src/qwt_graphic.h \
		/usr/local/qwt-6.1.0/src/qwt_null_paintdevice.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_map.h \
		/usr/local/qwt-6.1.0/src/qwt_transform.h \
		CheckpointMessages.h \
		VideoFrame.h \
		db_VideoFrame.h \
		LoginPassword.h \
		DbLoginPasswords.h \
		LoginDialog.h \
		ModelLoginPassword.h \
		TableEditDialog.h \
		ModelVisualParam.h \
		CheckPointEditDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_curve.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_seriesitem.h \
		/usr/local/qwt-6.1.0/src/qwt_series_data.h \
		/usr/local/qwt-6.1.0/src/qwt_samples.h \
		/usr/local/qwt-6.1.0/src/qwt_point_3d.h \
		/usr/local/qwt-6.1.0/src/qwt_point_polar.h \
		/usr/local/qwt-6.1.0/src/qwt_math.h \
		/usr/local/qwt-6.1.0/src/qwt_series_store.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_grid.h \
		/usr/local/qwt-6.1.0/src/qwt_symbol.h \
		/usr/local/qwt-6.1.0/src/qwt_legend.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_legend.h \
		ModelArchivSignal.h \
		DelegatArchivSignal.h \
		bitmapworker.h \
		mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_PromengDialog.cpp: AllHeaders.h \
		dbconn.h \
		db_VisualParam.h \
		VisualParam.h \
		Signal.h \
		db_signal.h \
		vec_signal.h \
		CheckPointProperties.h \
		db_CheckPointProperties.h \
		CheckpointPropDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_zoomer.h \
		/usr/local/qwt-6.1.0/src/qwt_global.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_text.h \
		/usr/local/qwt-6.1.0/src/qwt_event_pattern.h \
		plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_date.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_div.h \
		/usr/local/qwt-6.1.0/src/qwt_interval.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_dict.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_item.h \
		/usr/local/qwt-6.1.0/src/qwt_legend_data.h \
		/usr/local/qwt-6.1.0/src/qwt_graphic.h \
		/usr/local/qwt-6.1.0/src/qwt_null_paintdevice.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_map.h \
		/usr/local/qwt-6.1.0/src/qwt_transform.h \
		CheckpointMessages.h \
		VideoFrame.h \
		db_VideoFrame.h \
		LoginPassword.h \
		DbLoginPasswords.h \
		LoginDialog.h \
		ModelLoginPassword.h \
		TableEditDialog.h \
		ModelVisualParam.h \
		CheckPointEditDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_curve.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_seriesitem.h \
		/usr/local/qwt-6.1.0/src/qwt_series_data.h \
		/usr/local/qwt-6.1.0/src/qwt_samples.h \
		/usr/local/qwt-6.1.0/src/qwt_point_3d.h \
		/usr/local/qwt-6.1.0/src/qwt_point_polar.h \
		/usr/local/qwt-6.1.0/src/qwt_math.h \
		/usr/local/qwt-6.1.0/src/qwt_series_store.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_grid.h \
		/usr/local/qwt-6.1.0/src/qwt_symbol.h \
		/usr/local/qwt-6.1.0/src/qwt_legend.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_legend.h \
		ModelArchivSignal.h \
		DelegatArchivSignal.h \
		PromengDialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) PromengDialog.h -o moc_PromengDialog.cpp

moc_bitmapworker.cpp: AllHeaders.h \
		dbconn.h \
		db_VisualParam.h \
		VisualParam.h \
		Signal.h \
		db_signal.h \
		vec_signal.h \
		CheckPointProperties.h \
		db_CheckPointProperties.h \
		CheckpointPropDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_zoomer.h \
		/usr/local/qwt-6.1.0/src/qwt_global.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_text.h \
		/usr/local/qwt-6.1.0/src/qwt_event_pattern.h \
		plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_date.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_div.h \
		/usr/local/qwt-6.1.0/src/qwt_interval.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_dict.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_item.h \
		/usr/local/qwt-6.1.0/src/qwt_legend_data.h \
		/usr/local/qwt-6.1.0/src/qwt_graphic.h \
		/usr/local/qwt-6.1.0/src/qwt_null_paintdevice.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_map.h \
		/usr/local/qwt-6.1.0/src/qwt_transform.h \
		CheckpointMessages.h \
		VideoFrame.h \
		db_VideoFrame.h \
		LoginPassword.h \
		DbLoginPasswords.h \
		LoginDialog.h \
		ModelLoginPassword.h \
		TableEditDialog.h \
		ModelVisualParam.h \
		CheckPointEditDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_curve.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_seriesitem.h \
		/usr/local/qwt-6.1.0/src/qwt_series_data.h \
		/usr/local/qwt-6.1.0/src/qwt_samples.h \
		/usr/local/qwt-6.1.0/src/qwt_point_3d.h \
		/usr/local/qwt-6.1.0/src/qwt_point_polar.h \
		/usr/local/qwt-6.1.0/src/qwt_math.h \
		/usr/local/qwt-6.1.0/src/qwt_series_store.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_grid.h \
		/usr/local/qwt-6.1.0/src/qwt_symbol.h \
		/usr/local/qwt-6.1.0/src/qwt_legend.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_legend.h \
		ModelArchivSignal.h \
		DelegatArchivSignal.h \
		bitmapworker.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) bitmapworker.h -o moc_bitmapworker.cpp

moc_db_signal.cpp: AllHeaders.h \
		dbconn.h \
		db_VisualParam.h \
		VisualParam.h \
		Signal.h \
		db_signal.h \
		vec_signal.h \
		CheckPointProperties.h \
		db_CheckPointProperties.h \
		CheckpointPropDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_zoomer.h \
		/usr/local/qwt-6.1.0/src/qwt_global.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_text.h \
		/usr/local/qwt-6.1.0/src/qwt_event_pattern.h \
		plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_date.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_div.h \
		/usr/local/qwt-6.1.0/src/qwt_interval.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_dict.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_item.h \
		/usr/local/qwt-6.1.0/src/qwt_legend_data.h \
		/usr/local/qwt-6.1.0/src/qwt_graphic.h \
		/usr/local/qwt-6.1.0/src/qwt_null_paintdevice.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_map.h \
		/usr/local/qwt-6.1.0/src/qwt_transform.h \
		CheckpointMessages.h \
		VideoFrame.h \
		db_VideoFrame.h \
		LoginPassword.h \
		DbLoginPasswords.h \
		LoginDialog.h \
		ModelLoginPassword.h \
		TableEditDialog.h \
		ModelVisualParam.h \
		CheckPointEditDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_curve.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_seriesitem.h \
		/usr/local/qwt-6.1.0/src/qwt_series_data.h \
		/usr/local/qwt-6.1.0/src/qwt_samples.h \
		/usr/local/qwt-6.1.0/src/qwt_point_3d.h \
		/usr/local/qwt-6.1.0/src/qwt_point_polar.h \
		/usr/local/qwt-6.1.0/src/qwt_math.h \
		/usr/local/qwt-6.1.0/src/qwt_series_store.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_grid.h \
		/usr/local/qwt-6.1.0/src/qwt_symbol.h \
		/usr/local/qwt-6.1.0/src/qwt_legend.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_legend.h \
		ModelArchivSignal.h \
		DelegatArchivSignal.h \
		db_signal.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) db_signal.h -o moc_db_signal.cpp

moc_LoginDialog.cpp: AllHeaders.h \
		dbconn.h \
		db_VisualParam.h \
		VisualParam.h \
		Signal.h \
		db_signal.h \
		vec_signal.h \
		CheckPointProperties.h \
		db_CheckPointProperties.h \
		CheckpointPropDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_zoomer.h \
		/usr/local/qwt-6.1.0/src/qwt_global.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_text.h \
		/usr/local/qwt-6.1.0/src/qwt_event_pattern.h \
		plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_date.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_div.h \
		/usr/local/qwt-6.1.0/src/qwt_interval.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_dict.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_item.h \
		/usr/local/qwt-6.1.0/src/qwt_legend_data.h \
		/usr/local/qwt-6.1.0/src/qwt_graphic.h \
		/usr/local/qwt-6.1.0/src/qwt_null_paintdevice.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_map.h \
		/usr/local/qwt-6.1.0/src/qwt_transform.h \
		CheckpointMessages.h \
		VideoFrame.h \
		db_VideoFrame.h \
		LoginPassword.h \
		DbLoginPasswords.h \
		LoginDialog.h \
		ModelLoginPassword.h \
		TableEditDialog.h \
		ModelVisualParam.h \
		CheckPointEditDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_curve.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_seriesitem.h \
		/usr/local/qwt-6.1.0/src/qwt_series_data.h \
		/usr/local/qwt-6.1.0/src/qwt_samples.h \
		/usr/local/qwt-6.1.0/src/qwt_point_3d.h \
		/usr/local/qwt-6.1.0/src/qwt_point_polar.h \
		/usr/local/qwt-6.1.0/src/qwt_math.h \
		/usr/local/qwt-6.1.0/src/qwt_series_store.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_grid.h \
		/usr/local/qwt-6.1.0/src/qwt_symbol.h \
		/usr/local/qwt-6.1.0/src/qwt_legend.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_legend.h \
		ModelArchivSignal.h \
		DelegatArchivSignal.h \
		LoginDialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) LoginDialog.h -o moc_LoginDialog.cpp

moc_ModelLoginPassword.cpp: AllHeaders.h \
		dbconn.h \
		db_VisualParam.h \
		VisualParam.h \
		Signal.h \
		db_signal.h \
		vec_signal.h \
		CheckPointProperties.h \
		db_CheckPointProperties.h \
		CheckpointPropDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_zoomer.h \
		/usr/local/qwt-6.1.0/src/qwt_global.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_text.h \
		/usr/local/qwt-6.1.0/src/qwt_event_pattern.h \
		plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_date.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_div.h \
		/usr/local/qwt-6.1.0/src/qwt_interval.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_dict.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_item.h \
		/usr/local/qwt-6.1.0/src/qwt_legend_data.h \
		/usr/local/qwt-6.1.0/src/qwt_graphic.h \
		/usr/local/qwt-6.1.0/src/qwt_null_paintdevice.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_map.h \
		/usr/local/qwt-6.1.0/src/qwt_transform.h \
		CheckpointMessages.h \
		VideoFrame.h \
		db_VideoFrame.h \
		LoginPassword.h \
		DbLoginPasswords.h \
		LoginDialog.h \
		ModelLoginPassword.h \
		TableEditDialog.h \
		ModelVisualParam.h \
		CheckPointEditDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_curve.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_seriesitem.h \
		/usr/local/qwt-6.1.0/src/qwt_series_data.h \
		/usr/local/qwt-6.1.0/src/qwt_samples.h \
		/usr/local/qwt-6.1.0/src/qwt_point_3d.h \
		/usr/local/qwt-6.1.0/src/qwt_point_polar.h \
		/usr/local/qwt-6.1.0/src/qwt_math.h \
		/usr/local/qwt-6.1.0/src/qwt_series_store.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_grid.h \
		/usr/local/qwt-6.1.0/src/qwt_symbol.h \
		/usr/local/qwt-6.1.0/src/qwt_legend.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_legend.h \
		ModelArchivSignal.h \
		DelegatArchivSignal.h \
		ModelLoginPassword.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ModelLoginPassword.h -o moc_ModelLoginPassword.cpp

moc_TableEditDialog.cpp: AllHeaders.h \
		dbconn.h \
		db_VisualParam.h \
		VisualParam.h \
		Signal.h \
		db_signal.h \
		vec_signal.h \
		CheckPointProperties.h \
		db_CheckPointProperties.h \
		CheckpointPropDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_zoomer.h \
		/usr/local/qwt-6.1.0/src/qwt_global.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_text.h \
		/usr/local/qwt-6.1.0/src/qwt_event_pattern.h \
		plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_date.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_div.h \
		/usr/local/qwt-6.1.0/src/qwt_interval.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_dict.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_item.h \
		/usr/local/qwt-6.1.0/src/qwt_legend_data.h \
		/usr/local/qwt-6.1.0/src/qwt_graphic.h \
		/usr/local/qwt-6.1.0/src/qwt_null_paintdevice.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_map.h \
		/usr/local/qwt-6.1.0/src/qwt_transform.h \
		CheckpointMessages.h \
		VideoFrame.h \
		db_VideoFrame.h \
		LoginPassword.h \
		DbLoginPasswords.h \
		LoginDialog.h \
		ModelLoginPassword.h \
		TableEditDialog.h \
		ModelVisualParam.h \
		CheckPointEditDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_curve.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_seriesitem.h \
		/usr/local/qwt-6.1.0/src/qwt_series_data.h \
		/usr/local/qwt-6.1.0/src/qwt_samples.h \
		/usr/local/qwt-6.1.0/src/qwt_point_3d.h \
		/usr/local/qwt-6.1.0/src/qwt_point_polar.h \
		/usr/local/qwt-6.1.0/src/qwt_math.h \
		/usr/local/qwt-6.1.0/src/qwt_series_store.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_grid.h \
		/usr/local/qwt-6.1.0/src/qwt_symbol.h \
		/usr/local/qwt-6.1.0/src/qwt_legend.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_legend.h \
		ModelArchivSignal.h \
		DelegatArchivSignal.h \
		TableEditDialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) TableEditDialog.h -o moc_TableEditDialog.cpp

moc_ModelVisualParam.cpp: AllHeaders.h \
		dbconn.h \
		db_VisualParam.h \
		VisualParam.h \
		Signal.h \
		db_signal.h \
		vec_signal.h \
		CheckPointProperties.h \
		db_CheckPointProperties.h \
		CheckpointPropDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_zoomer.h \
		/usr/local/qwt-6.1.0/src/qwt_global.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_text.h \
		/usr/local/qwt-6.1.0/src/qwt_event_pattern.h \
		plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_date.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_div.h \
		/usr/local/qwt-6.1.0/src/qwt_interval.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_dict.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_item.h \
		/usr/local/qwt-6.1.0/src/qwt_legend_data.h \
		/usr/local/qwt-6.1.0/src/qwt_graphic.h \
		/usr/local/qwt-6.1.0/src/qwt_null_paintdevice.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_map.h \
		/usr/local/qwt-6.1.0/src/qwt_transform.h \
		CheckpointMessages.h \
		VideoFrame.h \
		db_VideoFrame.h \
		LoginPassword.h \
		DbLoginPasswords.h \
		LoginDialog.h \
		ModelLoginPassword.h \
		TableEditDialog.h \
		ModelVisualParam.h \
		CheckPointEditDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_curve.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_seriesitem.h \
		/usr/local/qwt-6.1.0/src/qwt_series_data.h \
		/usr/local/qwt-6.1.0/src/qwt_samples.h \
		/usr/local/qwt-6.1.0/src/qwt_point_3d.h \
		/usr/local/qwt-6.1.0/src/qwt_point_polar.h \
		/usr/local/qwt-6.1.0/src/qwt_math.h \
		/usr/local/qwt-6.1.0/src/qwt_series_store.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_grid.h \
		/usr/local/qwt-6.1.0/src/qwt_symbol.h \
		/usr/local/qwt-6.1.0/src/qwt_legend.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_legend.h \
		ModelArchivSignal.h \
		DelegatArchivSignal.h \
		ModelVisualParam.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ModelVisualParam.h -o moc_ModelVisualParam.cpp

moc_CheckPointEditDialog.cpp: AllHeaders.h \
		dbconn.h \
		db_VisualParam.h \
		VisualParam.h \
		Signal.h \
		db_signal.h \
		vec_signal.h \
		CheckPointProperties.h \
		db_CheckPointProperties.h \
		CheckpointPropDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_zoomer.h \
		/usr/local/qwt-6.1.0/src/qwt_global.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_text.h \
		/usr/local/qwt-6.1.0/src/qwt_event_pattern.h \
		plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_date.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_div.h \
		/usr/local/qwt-6.1.0/src/qwt_interval.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_dict.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_item.h \
		/usr/local/qwt-6.1.0/src/qwt_legend_data.h \
		/usr/local/qwt-6.1.0/src/qwt_graphic.h \
		/usr/local/qwt-6.1.0/src/qwt_null_paintdevice.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_map.h \
		/usr/local/qwt-6.1.0/src/qwt_transform.h \
		CheckpointMessages.h \
		VideoFrame.h \
		db_VideoFrame.h \
		LoginPassword.h \
		DbLoginPasswords.h \
		LoginDialog.h \
		ModelLoginPassword.h \
		TableEditDialog.h \
		ModelVisualParam.h \
		CheckPointEditDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_curve.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_seriesitem.h \
		/usr/local/qwt-6.1.0/src/qwt_series_data.h \
		/usr/local/qwt-6.1.0/src/qwt_samples.h \
		/usr/local/qwt-6.1.0/src/qwt_point_3d.h \
		/usr/local/qwt-6.1.0/src/qwt_point_polar.h \
		/usr/local/qwt-6.1.0/src/qwt_math.h \
		/usr/local/qwt-6.1.0/src/qwt_series_store.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_grid.h \
		/usr/local/qwt-6.1.0/src/qwt_symbol.h \
		/usr/local/qwt-6.1.0/src/qwt_legend.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_legend.h \
		ModelArchivSignal.h \
		DelegatArchivSignal.h \
		CheckPointEditDialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) CheckPointEditDialog.h -o moc_CheckPointEditDialog.cpp

moc_CheckpointPropDialog.cpp: /usr/local/qwt-6.1.0/src/qwt_plot_zoomer.h \
		/usr/local/qwt-6.1.0/src/qwt_global.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_text.h \
		/usr/local/qwt-6.1.0/src/qwt_event_pattern.h \
		AllHeaders.h \
		dbconn.h \
		db_VisualParam.h \
		VisualParam.h \
		Signal.h \
		db_signal.h \
		vec_signal.h \
		CheckPointProperties.h \
		db_CheckPointProperties.h \
		CheckpointPropDialog.h \
		plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_date.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_div.h \
		/usr/local/qwt-6.1.0/src/qwt_interval.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_dict.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_item.h \
		/usr/local/qwt-6.1.0/src/qwt_legend_data.h \
		/usr/local/qwt-6.1.0/src/qwt_graphic.h \
		/usr/local/qwt-6.1.0/src/qwt_null_paintdevice.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_map.h \
		/usr/local/qwt-6.1.0/src/qwt_transform.h \
		CheckpointMessages.h \
		VideoFrame.h \
		db_VideoFrame.h \
		LoginPassword.h \
		DbLoginPasswords.h \
		LoginDialog.h \
		ModelLoginPassword.h \
		TableEditDialog.h \
		ModelVisualParam.h \
		CheckPointEditDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_curve.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_seriesitem.h \
		/usr/local/qwt-6.1.0/src/qwt_series_data.h \
		/usr/local/qwt-6.1.0/src/qwt_samples.h \
		/usr/local/qwt-6.1.0/src/qwt_point_3d.h \
		/usr/local/qwt-6.1.0/src/qwt_point_polar.h \
		/usr/local/qwt-6.1.0/src/qwt_math.h \
		/usr/local/qwt-6.1.0/src/qwt_series_store.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_grid.h \
		/usr/local/qwt-6.1.0/src/qwt_symbol.h \
		/usr/local/qwt-6.1.0/src/qwt_legend.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_legend.h \
		ModelArchivSignal.h \
		DelegatArchivSignal.h \
		CheckpointPropDialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) CheckpointPropDialog.h -o moc_CheckpointPropDialog.cpp

moc_plot.cpp: AllHeaders.h \
		dbconn.h \
		db_VisualParam.h \
		VisualParam.h \
		Signal.h \
		db_signal.h \
		vec_signal.h \
		CheckPointProperties.h \
		db_CheckPointProperties.h \
		CheckpointPropDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_zoomer.h \
		/usr/local/qwt-6.1.0/src/qwt_global.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_text.h \
		/usr/local/qwt-6.1.0/src/qwt_event_pattern.h \
		plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_date.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_div.h \
		/usr/local/qwt-6.1.0/src/qwt_interval.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_dict.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_item.h \
		/usr/local/qwt-6.1.0/src/qwt_legend_data.h \
		/usr/local/qwt-6.1.0/src/qwt_graphic.h \
		/usr/local/qwt-6.1.0/src/qwt_null_paintdevice.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_map.h \
		/usr/local/qwt-6.1.0/src/qwt_transform.h \
		CheckpointMessages.h \
		VideoFrame.h \
		db_VideoFrame.h \
		LoginPassword.h \
		DbLoginPasswords.h \
		LoginDialog.h \
		ModelLoginPassword.h \
		TableEditDialog.h \
		ModelVisualParam.h \
		CheckPointEditDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_curve.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_seriesitem.h \
		/usr/local/qwt-6.1.0/src/qwt_series_data.h \
		/usr/local/qwt-6.1.0/src/qwt_samples.h \
		/usr/local/qwt-6.1.0/src/qwt_point_3d.h \
		/usr/local/qwt-6.1.0/src/qwt_point_polar.h \
		/usr/local/qwt-6.1.0/src/qwt_math.h \
		/usr/local/qwt-6.1.0/src/qwt_series_store.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_grid.h \
		/usr/local/qwt-6.1.0/src/qwt_symbol.h \
		/usr/local/qwt-6.1.0/src/qwt_legend.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_legend.h \
		ModelArchivSignal.h \
		DelegatArchivSignal.h \
		plot.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) plot.h -o moc_plot.cpp

moc_ModelArchivSignal.cpp: AllHeaders.h \
		dbconn.h \
		db_VisualParam.h \
		VisualParam.h \
		Signal.h \
		db_signal.h \
		vec_signal.h \
		CheckPointProperties.h \
		db_CheckPointProperties.h \
		CheckpointPropDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_zoomer.h \
		/usr/local/qwt-6.1.0/src/qwt_global.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_text.h \
		/usr/local/qwt-6.1.0/src/qwt_event_pattern.h \
		plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_date.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_div.h \
		/usr/local/qwt-6.1.0/src/qwt_interval.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_dict.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_item.h \
		/usr/local/qwt-6.1.0/src/qwt_legend_data.h \
		/usr/local/qwt-6.1.0/src/qwt_graphic.h \
		/usr/local/qwt-6.1.0/src/qwt_null_paintdevice.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_map.h \
		/usr/local/qwt-6.1.0/src/qwt_transform.h \
		CheckpointMessages.h \
		VideoFrame.h \
		db_VideoFrame.h \
		LoginPassword.h \
		DbLoginPasswords.h \
		LoginDialog.h \
		ModelLoginPassword.h \
		TableEditDialog.h \
		ModelVisualParam.h \
		CheckPointEditDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_curve.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_seriesitem.h \
		/usr/local/qwt-6.1.0/src/qwt_series_data.h \
		/usr/local/qwt-6.1.0/src/qwt_samples.h \
		/usr/local/qwt-6.1.0/src/qwt_point_3d.h \
		/usr/local/qwt-6.1.0/src/qwt_point_polar.h \
		/usr/local/qwt-6.1.0/src/qwt_math.h \
		/usr/local/qwt-6.1.0/src/qwt_series_store.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_grid.h \
		/usr/local/qwt-6.1.0/src/qwt_symbol.h \
		/usr/local/qwt-6.1.0/src/qwt_legend.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_legend.h \
		ModelArchivSignal.h \
		DelegatArchivSignal.h \
		ModelArchivSignal.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) ModelArchivSignal.h -o moc_ModelArchivSignal.cpp

moc_DelegatArchivSignal.cpp: DelegatArchivSignal.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) DelegatArchivSignal.h -o moc_DelegatArchivSignal.cpp

compiler_rcc_make_all: qrc_application.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_application.cpp
qrc_application.cpp: application.qrc \
		resources/Truba.bmp \
		resources/6.4.bmp \
		resources/MeteoB_NEW.bmp \
		resources/1.0.bmp \
		resources/Map1_new.bmp \
		resources/AsrkroLogoPanel.bmp \
		resources/Map2_new.bmp \
		resources/VentFull.bmp \
		resources/4.4.bmp \
		resources/images/2.bmp \
		resources/images/3.bmp \
		resources/images/5.bmp \
		resources/images/6.bmp \
		resources/images/29.bmp \
		images/new.png \
		images/copy.png \
		images/cut.png \
		images/save.png \
		images/paste.png \
		images/open.png
	/usr/bin/rcc -name application application.qrc -o qrc_application.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		PromengDialog.h \
		AllHeaders.h \
		dbconn.h \
		db_VisualParam.h \
		VisualParam.h \
		Signal.h \
		db_signal.h \
		vec_signal.h \
		CheckPointProperties.h \
		db_CheckPointProperties.h \
		CheckpointPropDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_zoomer.h \
		/usr/local/qwt-6.1.0/src/qwt_global.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_text.h \
		/usr/local/qwt-6.1.0/src/qwt_event_pattern.h \
		plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_date.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_div.h \
		/usr/local/qwt-6.1.0/src/qwt_interval.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_dict.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_item.h \
		/usr/local/qwt-6.1.0/src/qwt_legend_data.h \
		/usr/local/qwt-6.1.0/src/qwt_graphic.h \
		/usr/local/qwt-6.1.0/src/qwt_null_paintdevice.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_map.h \
		/usr/local/qwt-6.1.0/src/qwt_transform.h \
		CheckpointMessages.h \
		VideoFrame.h \
		db_VideoFrame.h \
		LoginPassword.h \
		DbLoginPasswords.h \
		LoginDialog.h \
		ModelLoginPassword.h \
		TableEditDialog.h \
		ModelVisualParam.h \
		CheckPointEditDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_curve.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_seriesitem.h \
		/usr/local/qwt-6.1.0/src/qwt_series_data.h \
		/usr/local/qwt-6.1.0/src/qwt_samples.h \
		/usr/local/qwt-6.1.0/src/qwt_point_3d.h \
		/usr/local/qwt-6.1.0/src/qwt_point_polar.h \
		/usr/local/qwt-6.1.0/src/qwt_math.h \
		/usr/local/qwt-6.1.0/src/qwt_series_store.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_grid.h \
		/usr/local/qwt-6.1.0/src/qwt_symbol.h \
		/usr/local/qwt-6.1.0/src/qwt_legend.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_legend.h \
		ModelArchivSignal.h \
		DelegatArchivSignal.h \
		bitmapworker.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		PromengDialog.h \
		AllHeaders.h \
		dbconn.h \
		db_VisualParam.h \
		VisualParam.h \
		Signal.h \
		db_signal.h \
		vec_signal.h \
		CheckPointProperties.h \
		db_CheckPointProperties.h \
		CheckpointPropDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_zoomer.h \
		/usr/local/qwt-6.1.0/src/qwt_global.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_text.h \
		/usr/local/qwt-6.1.0/src/qwt_event_pattern.h \
		plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_date.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_div.h \
		/usr/local/qwt-6.1.0/src/qwt_interval.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_dict.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_item.h \
		/usr/local/qwt-6.1.0/src/qwt_legend_data.h \
		/usr/local/qwt-6.1.0/src/qwt_graphic.h \
		/usr/local/qwt-6.1.0/src/qwt_null_paintdevice.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_map.h \
		/usr/local/qwt-6.1.0/src/qwt_transform.h \
		CheckpointMessages.h \
		VideoFrame.h \
		db_VideoFrame.h \
		LoginPassword.h \
		DbLoginPasswords.h \
		LoginDialog.h \
		ModelLoginPassword.h \
		TableEditDialog.h \
		ModelVisualParam.h \
		CheckPointEditDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_curve.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_seriesitem.h \
		/usr/local/qwt-6.1.0/src/qwt_series_data.h \
		/usr/local/qwt-6.1.0/src/qwt_samples.h \
		/usr/local/qwt-6.1.0/src/qwt_point_3d.h \
		/usr/local/qwt-6.1.0/src/qwt_point_polar.h \
		/usr/local/qwt-6.1.0/src/qwt_math.h \
		/usr/local/qwt-6.1.0/src/qwt_series_store.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_grid.h \
		/usr/local/qwt-6.1.0/src/qwt_symbol.h \
		/usr/local/qwt-6.1.0/src/qwt_legend.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_legend.h \
		ModelArchivSignal.h \
		DelegatArchivSignal.h \
		bitmapworker.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

PromengDialog.o: PromengDialog.cpp PromengDialog.h \
		AllHeaders.h \
		dbconn.h \
		db_VisualParam.h \
		VisualParam.h \
		Signal.h \
		db_signal.h \
		vec_signal.h \
		CheckPointProperties.h \
		db_CheckPointProperties.h \
		CheckpointPropDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_zoomer.h \
		/usr/local/qwt-6.1.0/src/qwt_global.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_text.h \
		/usr/local/qwt-6.1.0/src/qwt_event_pattern.h \
		plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_date.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_div.h \
		/usr/local/qwt-6.1.0/src/qwt_interval.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_dict.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_item.h \
		/usr/local/qwt-6.1.0/src/qwt_legend_data.h \
		/usr/local/qwt-6.1.0/src/qwt_graphic.h \
		/usr/local/qwt-6.1.0/src/qwt_null_paintdevice.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_map.h \
		/usr/local/qwt-6.1.0/src/qwt_transform.h \
		CheckpointMessages.h \
		VideoFrame.h \
		db_VideoFrame.h \
		LoginPassword.h \
		DbLoginPasswords.h \
		LoginDialog.h \
		ModelLoginPassword.h \
		TableEditDialog.h \
		ModelVisualParam.h \
		CheckPointEditDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_curve.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_seriesitem.h \
		/usr/local/qwt-6.1.0/src/qwt_series_data.h \
		/usr/local/qwt-6.1.0/src/qwt_samples.h \
		/usr/local/qwt-6.1.0/src/qwt_point_3d.h \
		/usr/local/qwt-6.1.0/src/qwt_point_polar.h \
		/usr/local/qwt-6.1.0/src/qwt_math.h \
		/usr/local/qwt-6.1.0/src/qwt_series_store.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_grid.h \
		/usr/local/qwt-6.1.0/src/qwt_symbol.h \
		/usr/local/qwt-6.1.0/src/qwt_legend.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_legend.h \
		ModelArchivSignal.h \
		DelegatArchivSignal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PromengDialog.o PromengDialog.cpp

bitmapworker.o: bitmapworker.cpp bitmapworker.h \
		AllHeaders.h \
		dbconn.h \
		db_VisualParam.h \
		VisualParam.h \
		Signal.h \
		db_signal.h \
		vec_signal.h \
		CheckPointProperties.h \
		db_CheckPointProperties.h \
		CheckpointPropDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_zoomer.h \
		/usr/local/qwt-6.1.0/src/qwt_global.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_text.h \
		/usr/local/qwt-6.1.0/src/qwt_event_pattern.h \
		plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_date.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_div.h \
		/usr/local/qwt-6.1.0/src/qwt_interval.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_dict.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_item.h \
		/usr/local/qwt-6.1.0/src/qwt_legend_data.h \
		/usr/local/qwt-6.1.0/src/qwt_graphic.h \
		/usr/local/qwt-6.1.0/src/qwt_null_paintdevice.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_map.h \
		/usr/local/qwt-6.1.0/src/qwt_transform.h \
		CheckpointMessages.h \
		VideoFrame.h \
		db_VideoFrame.h \
		LoginPassword.h \
		DbLoginPasswords.h \
		LoginDialog.h \
		ModelLoginPassword.h \
		TableEditDialog.h \
		ModelVisualParam.h \
		CheckPointEditDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_curve.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_seriesitem.h \
		/usr/local/qwt-6.1.0/src/qwt_series_data.h \
		/usr/local/qwt-6.1.0/src/qwt_samples.h \
		/usr/local/qwt-6.1.0/src/qwt_point_3d.h \
		/usr/local/qwt-6.1.0/src/qwt_point_polar.h \
		/usr/local/qwt-6.1.0/src/qwt_math.h \
		/usr/local/qwt-6.1.0/src/qwt_series_store.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_grid.h \
		/usr/local/qwt-6.1.0/src/qwt_symbol.h \
		/usr/local/qwt-6.1.0/src/qwt_legend.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_legend.h \
		ModelArchivSignal.h \
		DelegatArchivSignal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bitmapworker.o bitmapworker.cpp

db_VisualParam.o: db_VisualParam.cpp db_VisualParam.h \
		VisualParam.h \
		AllHeaders.h \
		dbconn.h \
		Signal.h \
		db_signal.h \
		vec_signal.h \
		CheckPointProperties.h \
		db_CheckPointProperties.h \
		CheckpointPropDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_zoomer.h \
		/usr/local/qwt-6.1.0/src/qwt_global.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_text.h \
		/usr/local/qwt-6.1.0/src/qwt_event_pattern.h \
		plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_date.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_div.h \
		/usr/local/qwt-6.1.0/src/qwt_interval.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_dict.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_item.h \
		/usr/local/qwt-6.1.0/src/qwt_legend_data.h \
		/usr/local/qwt-6.1.0/src/qwt_graphic.h \
		/usr/local/qwt-6.1.0/src/qwt_null_paintdevice.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_map.h \
		/usr/local/qwt-6.1.0/src/qwt_transform.h \
		CheckpointMessages.h \
		VideoFrame.h \
		db_VideoFrame.h \
		LoginPassword.h \
		DbLoginPasswords.h \
		LoginDialog.h \
		ModelLoginPassword.h \
		TableEditDialog.h \
		ModelVisualParam.h \
		CheckPointEditDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_curve.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_seriesitem.h \
		/usr/local/qwt-6.1.0/src/qwt_series_data.h \
		/usr/local/qwt-6.1.0/src/qwt_samples.h \
		/usr/local/qwt-6.1.0/src/qwt_point_3d.h \
		/usr/local/qwt-6.1.0/src/qwt_point_polar.h \
		/usr/local/qwt-6.1.0/src/qwt_math.h \
		/usr/local/qwt-6.1.0/src/qwt_series_store.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_grid.h \
		/usr/local/qwt-6.1.0/src/qwt_symbol.h \
		/usr/local/qwt-6.1.0/src/qwt_legend.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_legend.h \
		ModelArchivSignal.h \
		DelegatArchivSignal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o db_VisualParam.o db_VisualParam.cpp

dbconn.o: dbconn.cpp dbconn.h \
		AllHeaders.h \
		db_VisualParam.h \
		VisualParam.h \
		Signal.h \
		db_signal.h \
		vec_signal.h \
		CheckPointProperties.h \
		db_CheckPointProperties.h \
		CheckpointPropDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_zoomer.h \
		/usr/local/qwt-6.1.0/src/qwt_global.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_text.h \
		/usr/local/qwt-6.1.0/src/qwt_event_pattern.h \
		plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_date.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_div.h \
		/usr/local/qwt-6.1.0/src/qwt_interval.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_dict.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_item.h \
		/usr/local/qwt-6.1.0/src/qwt_legend_data.h \
		/usr/local/qwt-6.1.0/src/qwt_graphic.h \
		/usr/local/qwt-6.1.0/src/qwt_null_paintdevice.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_map.h \
		/usr/local/qwt-6.1.0/src/qwt_transform.h \
		CheckpointMessages.h \
		VideoFrame.h \
		db_VideoFrame.h \
		LoginPassword.h \
		DbLoginPasswords.h \
		LoginDialog.h \
		ModelLoginPassword.h \
		TableEditDialog.h \
		ModelVisualParam.h \
		CheckPointEditDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_curve.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_seriesitem.h \
		/usr/local/qwt-6.1.0/src/qwt_series_data.h \
		/usr/local/qwt-6.1.0/src/qwt_samples.h \
		/usr/local/qwt-6.1.0/src/qwt_point_3d.h \
		/usr/local/qwt-6.1.0/src/qwt_point_polar.h \
		/usr/local/qwt-6.1.0/src/qwt_math.h \
		/usr/local/qwt-6.1.0/src/qwt_series_store.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_grid.h \
		/usr/local/qwt-6.1.0/src/qwt_symbol.h \
		/usr/local/qwt-6.1.0/src/qwt_legend.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_legend.h \
		ModelArchivSignal.h \
		DelegatArchivSignal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dbconn.o dbconn.cpp

db_signal.o: db_signal.cpp db_signal.h \
		AllHeaders.h \
		dbconn.h \
		db_VisualParam.h \
		VisualParam.h \
		Signal.h \
		CheckPointProperties.h \
		db_CheckPointProperties.h \
		CheckpointPropDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_zoomer.h \
		/usr/local/qwt-6.1.0/src/qwt_global.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_text.h \
		/usr/local/qwt-6.1.0/src/qwt_event_pattern.h \
		plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_date.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_div.h \
		/usr/local/qwt-6.1.0/src/qwt_interval.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_dict.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_item.h \
		/usr/local/qwt-6.1.0/src/qwt_legend_data.h \
		/usr/local/qwt-6.1.0/src/qwt_graphic.h \
		/usr/local/qwt-6.1.0/src/qwt_null_paintdevice.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_map.h \
		/usr/local/qwt-6.1.0/src/qwt_transform.h \
		vec_signal.h \
		CheckpointMessages.h \
		VideoFrame.h \
		db_VideoFrame.h \
		LoginPassword.h \
		DbLoginPasswords.h \
		LoginDialog.h \
		ModelLoginPassword.h \
		TableEditDialog.h \
		ModelVisualParam.h \
		CheckPointEditDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_curve.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_seriesitem.h \
		/usr/local/qwt-6.1.0/src/qwt_series_data.h \
		/usr/local/qwt-6.1.0/src/qwt_samples.h \
		/usr/local/qwt-6.1.0/src/qwt_point_3d.h \
		/usr/local/qwt-6.1.0/src/qwt_point_polar.h \
		/usr/local/qwt-6.1.0/src/qwt_math.h \
		/usr/local/qwt-6.1.0/src/qwt_series_store.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_grid.h \
		/usr/local/qwt-6.1.0/src/qwt_symbol.h \
		/usr/local/qwt-6.1.0/src/qwt_legend.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_legend.h \
		ModelArchivSignal.h \
		DelegatArchivSignal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o db_signal.o db_signal.cpp

CheckpointMessages.o: CheckpointMessages.cpp CheckpointMessages.h \
		AllHeaders.h \
		dbconn.h \
		db_VisualParam.h \
		VisualParam.h \
		Signal.h \
		db_signal.h \
		vec_signal.h \
		CheckPointProperties.h \
		db_CheckPointProperties.h \
		CheckpointPropDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_zoomer.h \
		/usr/local/qwt-6.1.0/src/qwt_global.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_text.h \
		/usr/local/qwt-6.1.0/src/qwt_event_pattern.h \
		plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_date.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_div.h \
		/usr/local/qwt-6.1.0/src/qwt_interval.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_dict.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_item.h \
		/usr/local/qwt-6.1.0/src/qwt_legend_data.h \
		/usr/local/qwt-6.1.0/src/qwt_graphic.h \
		/usr/local/qwt-6.1.0/src/qwt_null_paintdevice.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_map.h \
		/usr/local/qwt-6.1.0/src/qwt_transform.h \
		VideoFrame.h \
		db_VideoFrame.h \
		LoginPassword.h \
		DbLoginPasswords.h \
		LoginDialog.h \
		ModelLoginPassword.h \
		TableEditDialog.h \
		ModelVisualParam.h \
		CheckPointEditDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_curve.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_seriesitem.h \
		/usr/local/qwt-6.1.0/src/qwt_series_data.h \
		/usr/local/qwt-6.1.0/src/qwt_samples.h \
		/usr/local/qwt-6.1.0/src/qwt_point_3d.h \
		/usr/local/qwt-6.1.0/src/qwt_point_polar.h \
		/usr/local/qwt-6.1.0/src/qwt_math.h \
		/usr/local/qwt-6.1.0/src/qwt_series_store.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_grid.h \
		/usr/local/qwt-6.1.0/src/qwt_symbol.h \
		/usr/local/qwt-6.1.0/src/qwt_legend.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_legend.h \
		ModelArchivSignal.h \
		DelegatArchivSignal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CheckpointMessages.o CheckpointMessages.cpp

CheckPointProperties.o: CheckPointProperties.cpp CheckPointProperties.h \
		AllHeaders.h \
		dbconn.h \
		db_VisualParam.h \
		VisualParam.h \
		Signal.h \
		db_signal.h \
		vec_signal.h \
		db_CheckPointProperties.h \
		CheckpointPropDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_zoomer.h \
		/usr/local/qwt-6.1.0/src/qwt_global.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_text.h \
		/usr/local/qwt-6.1.0/src/qwt_event_pattern.h \
		plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_date.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_div.h \
		/usr/local/qwt-6.1.0/src/qwt_interval.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_dict.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_item.h \
		/usr/local/qwt-6.1.0/src/qwt_legend_data.h \
		/usr/local/qwt-6.1.0/src/qwt_graphic.h \
		/usr/local/qwt-6.1.0/src/qwt_null_paintdevice.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_map.h \
		/usr/local/qwt-6.1.0/src/qwt_transform.h \
		CheckpointMessages.h \
		VideoFrame.h \
		db_VideoFrame.h \
		LoginPassword.h \
		DbLoginPasswords.h \
		LoginDialog.h \
		ModelLoginPassword.h \
		TableEditDialog.h \
		ModelVisualParam.h \
		CheckPointEditDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_curve.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_seriesitem.h \
		/usr/local/qwt-6.1.0/src/qwt_series_data.h \
		/usr/local/qwt-6.1.0/src/qwt_samples.h \
		/usr/local/qwt-6.1.0/src/qwt_point_3d.h \
		/usr/local/qwt-6.1.0/src/qwt_point_polar.h \
		/usr/local/qwt-6.1.0/src/qwt_math.h \
		/usr/local/qwt-6.1.0/src/qwt_series_store.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_grid.h \
		/usr/local/qwt-6.1.0/src/qwt_symbol.h \
		/usr/local/qwt-6.1.0/src/qwt_legend.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_legend.h \
		ModelArchivSignal.h \
		DelegatArchivSignal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CheckPointProperties.o CheckPointProperties.cpp

db_CheckPointProperties.o: db_CheckPointProperties.cpp db_CheckPointProperties.h \
		CheckPointProperties.h \
		AllHeaders.h \
		dbconn.h \
		db_VisualParam.h \
		VisualParam.h \
		Signal.h \
		db_signal.h \
		vec_signal.h \
		CheckpointPropDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_zoomer.h \
		/usr/local/qwt-6.1.0/src/qwt_global.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_text.h \
		/usr/local/qwt-6.1.0/src/qwt_event_pattern.h \
		plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_date.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_div.h \
		/usr/local/qwt-6.1.0/src/qwt_interval.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_dict.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_item.h \
		/usr/local/qwt-6.1.0/src/qwt_legend_data.h \
		/usr/local/qwt-6.1.0/src/qwt_graphic.h \
		/usr/local/qwt-6.1.0/src/qwt_null_paintdevice.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_map.h \
		/usr/local/qwt-6.1.0/src/qwt_transform.h \
		CheckpointMessages.h \
		VideoFrame.h \
		db_VideoFrame.h \
		LoginPassword.h \
		DbLoginPasswords.h \
		LoginDialog.h \
		ModelLoginPassword.h \
		TableEditDialog.h \
		ModelVisualParam.h \
		CheckPointEditDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_curve.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_seriesitem.h \
		/usr/local/qwt-6.1.0/src/qwt_series_data.h \
		/usr/local/qwt-6.1.0/src/qwt_samples.h \
		/usr/local/qwt-6.1.0/src/qwt_point_3d.h \
		/usr/local/qwt-6.1.0/src/qwt_point_polar.h \
		/usr/local/qwt-6.1.0/src/qwt_math.h \
		/usr/local/qwt-6.1.0/src/qwt_series_store.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_grid.h \
		/usr/local/qwt-6.1.0/src/qwt_symbol.h \
		/usr/local/qwt-6.1.0/src/qwt_legend.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_legend.h \
		ModelArchivSignal.h \
		DelegatArchivSignal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o db_CheckPointProperties.o db_CheckPointProperties.cpp

vec_signal.o: vec_signal.cpp vec_signal.h \
		Signal.h \
		AllHeaders.h \
		dbconn.h \
		db_VisualParam.h \
		VisualParam.h \
		db_signal.h \
		CheckPointProperties.h \
		db_CheckPointProperties.h \
		CheckpointPropDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_zoomer.h \
		/usr/local/qwt-6.1.0/src/qwt_global.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_text.h \
		/usr/local/qwt-6.1.0/src/qwt_event_pattern.h \
		plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_date.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_div.h \
		/usr/local/qwt-6.1.0/src/qwt_interval.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_dict.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_item.h \
		/usr/local/qwt-6.1.0/src/qwt_legend_data.h \
		/usr/local/qwt-6.1.0/src/qwt_graphic.h \
		/usr/local/qwt-6.1.0/src/qwt_null_paintdevice.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_map.h \
		/usr/local/qwt-6.1.0/src/qwt_transform.h \
		CheckpointMessages.h \
		VideoFrame.h \
		db_VideoFrame.h \
		LoginPassword.h \
		DbLoginPasswords.h \
		LoginDialog.h \
		ModelLoginPassword.h \
		TableEditDialog.h \
		ModelVisualParam.h \
		CheckPointEditDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_curve.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_seriesitem.h \
		/usr/local/qwt-6.1.0/src/qwt_series_data.h \
		/usr/local/qwt-6.1.0/src/qwt_samples.h \
		/usr/local/qwt-6.1.0/src/qwt_point_3d.h \
		/usr/local/qwt-6.1.0/src/qwt_point_polar.h \
		/usr/local/qwt-6.1.0/src/qwt_math.h \
		/usr/local/qwt-6.1.0/src/qwt_series_store.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_grid.h \
		/usr/local/qwt-6.1.0/src/qwt_symbol.h \
		/usr/local/qwt-6.1.0/src/qwt_legend.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_legend.h \
		ModelArchivSignal.h \
		DelegatArchivSignal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vec_signal.o vec_signal.cpp

db_VideoFrame.o: db_VideoFrame.cpp db_VideoFrame.h \
		AllHeaders.h \
		dbconn.h \
		db_VisualParam.h \
		VisualParam.h \
		Signal.h \
		db_signal.h \
		vec_signal.h \
		CheckPointProperties.h \
		db_CheckPointProperties.h \
		CheckpointPropDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_zoomer.h \
		/usr/local/qwt-6.1.0/src/qwt_global.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_text.h \
		/usr/local/qwt-6.1.0/src/qwt_event_pattern.h \
		plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_date.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_div.h \
		/usr/local/qwt-6.1.0/src/qwt_interval.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_dict.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_item.h \
		/usr/local/qwt-6.1.0/src/qwt_legend_data.h \
		/usr/local/qwt-6.1.0/src/qwt_graphic.h \
		/usr/local/qwt-6.1.0/src/qwt_null_paintdevice.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_map.h \
		/usr/local/qwt-6.1.0/src/qwt_transform.h \
		CheckpointMessages.h \
		VideoFrame.h \
		LoginPassword.h \
		DbLoginPasswords.h \
		LoginDialog.h \
		ModelLoginPassword.h \
		TableEditDialog.h \
		ModelVisualParam.h \
		CheckPointEditDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_curve.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_seriesitem.h \
		/usr/local/qwt-6.1.0/src/qwt_series_data.h \
		/usr/local/qwt-6.1.0/src/qwt_samples.h \
		/usr/local/qwt-6.1.0/src/qwt_point_3d.h \
		/usr/local/qwt-6.1.0/src/qwt_point_polar.h \
		/usr/local/qwt-6.1.0/src/qwt_math.h \
		/usr/local/qwt-6.1.0/src/qwt_series_store.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_grid.h \
		/usr/local/qwt-6.1.0/src/qwt_symbol.h \
		/usr/local/qwt-6.1.0/src/qwt_legend.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_legend.h \
		ModelArchivSignal.h \
		DelegatArchivSignal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o db_VideoFrame.o db_VideoFrame.cpp

VideoFrame.o: VideoFrame.cpp VideoFrame.h \
		AllHeaders.h \
		dbconn.h \
		db_VisualParam.h \
		VisualParam.h \
		Signal.h \
		db_signal.h \
		vec_signal.h \
		CheckPointProperties.h \
		db_CheckPointProperties.h \
		CheckpointPropDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_zoomer.h \
		/usr/local/qwt-6.1.0/src/qwt_global.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_text.h \
		/usr/local/qwt-6.1.0/src/qwt_event_pattern.h \
		plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_date.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_div.h \
		/usr/local/qwt-6.1.0/src/qwt_interval.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_dict.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_item.h \
		/usr/local/qwt-6.1.0/src/qwt_legend_data.h \
		/usr/local/qwt-6.1.0/src/qwt_graphic.h \
		/usr/local/qwt-6.1.0/src/qwt_null_paintdevice.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_map.h \
		/usr/local/qwt-6.1.0/src/qwt_transform.h \
		CheckpointMessages.h \
		db_VideoFrame.h \
		LoginPassword.h \
		DbLoginPasswords.h \
		LoginDialog.h \
		ModelLoginPassword.h \
		TableEditDialog.h \
		ModelVisualParam.h \
		CheckPointEditDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_curve.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_seriesitem.h \
		/usr/local/qwt-6.1.0/src/qwt_series_data.h \
		/usr/local/qwt-6.1.0/src/qwt_samples.h \
		/usr/local/qwt-6.1.0/src/qwt_point_3d.h \
		/usr/local/qwt-6.1.0/src/qwt_point_polar.h \
		/usr/local/qwt-6.1.0/src/qwt_math.h \
		/usr/local/qwt-6.1.0/src/qwt_series_store.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_grid.h \
		/usr/local/qwt-6.1.0/src/qwt_symbol.h \
		/usr/local/qwt-6.1.0/src/qwt_legend.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_legend.h \
		ModelArchivSignal.h \
		DelegatArchivSignal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o VideoFrame.o VideoFrame.cpp

VisualParam.o: VisualParam.cpp VisualParam.h \
		AllHeaders.h \
		dbconn.h \
		db_VisualParam.h \
		Signal.h \
		db_signal.h \
		vec_signal.h \
		CheckPointProperties.h \
		db_CheckPointProperties.h \
		CheckpointPropDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_zoomer.h \
		/usr/local/qwt-6.1.0/src/qwt_global.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_text.h \
		/usr/local/qwt-6.1.0/src/qwt_event_pattern.h \
		plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_date.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_div.h \
		/usr/local/qwt-6.1.0/src/qwt_interval.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_dict.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_item.h \
		/usr/local/qwt-6.1.0/src/qwt_legend_data.h \
		/usr/local/qwt-6.1.0/src/qwt_graphic.h \
		/usr/local/qwt-6.1.0/src/qwt_null_paintdevice.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_map.h \
		/usr/local/qwt-6.1.0/src/qwt_transform.h \
		CheckpointMessages.h \
		VideoFrame.h \
		db_VideoFrame.h \
		LoginPassword.h \
		DbLoginPasswords.h \
		LoginDialog.h \
		ModelLoginPassword.h \
		TableEditDialog.h \
		ModelVisualParam.h \
		CheckPointEditDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_curve.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_seriesitem.h \
		/usr/local/qwt-6.1.0/src/qwt_series_data.h \
		/usr/local/qwt-6.1.0/src/qwt_samples.h \
		/usr/local/qwt-6.1.0/src/qwt_point_3d.h \
		/usr/local/qwt-6.1.0/src/qwt_point_polar.h \
		/usr/local/qwt-6.1.0/src/qwt_math.h \
		/usr/local/qwt-6.1.0/src/qwt_series_store.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_grid.h \
		/usr/local/qwt-6.1.0/src/qwt_symbol.h \
		/usr/local/qwt-6.1.0/src/qwt_legend.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_legend.h \
		ModelArchivSignal.h \
		DelegatArchivSignal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o VisualParam.o VisualParam.cpp

LoginPassword.o: LoginPassword.cpp LoginPassword.h \
		AllHeaders.h \
		dbconn.h \
		db_VisualParam.h \
		VisualParam.h \
		Signal.h \
		db_signal.h \
		vec_signal.h \
		CheckPointProperties.h \
		db_CheckPointProperties.h \
		CheckpointPropDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_zoomer.h \
		/usr/local/qwt-6.1.0/src/qwt_global.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_text.h \
		/usr/local/qwt-6.1.0/src/qwt_event_pattern.h \
		plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_date.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_div.h \
		/usr/local/qwt-6.1.0/src/qwt_interval.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_dict.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_item.h \
		/usr/local/qwt-6.1.0/src/qwt_legend_data.h \
		/usr/local/qwt-6.1.0/src/qwt_graphic.h \
		/usr/local/qwt-6.1.0/src/qwt_null_paintdevice.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_map.h \
		/usr/local/qwt-6.1.0/src/qwt_transform.h \
		CheckpointMessages.h \
		VideoFrame.h \
		db_VideoFrame.h \
		DbLoginPasswords.h \
		LoginDialog.h \
		ModelLoginPassword.h \
		TableEditDialog.h \
		ModelVisualParam.h \
		CheckPointEditDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_curve.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_seriesitem.h \
		/usr/local/qwt-6.1.0/src/qwt_series_data.h \
		/usr/local/qwt-6.1.0/src/qwt_samples.h \
		/usr/local/qwt-6.1.0/src/qwt_point_3d.h \
		/usr/local/qwt-6.1.0/src/qwt_point_polar.h \
		/usr/local/qwt-6.1.0/src/qwt_math.h \
		/usr/local/qwt-6.1.0/src/qwt_series_store.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_grid.h \
		/usr/local/qwt-6.1.0/src/qwt_symbol.h \
		/usr/local/qwt-6.1.0/src/qwt_legend.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_legend.h \
		ModelArchivSignal.h \
		DelegatArchivSignal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o LoginPassword.o LoginPassword.cpp

DbLoginPasswords.o: DbLoginPasswords.cpp DbLoginPasswords.h \
		AllHeaders.h \
		dbconn.h \
		db_VisualParam.h \
		VisualParam.h \
		Signal.h \
		db_signal.h \
		vec_signal.h \
		CheckPointProperties.h \
		db_CheckPointProperties.h \
		CheckpointPropDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_zoomer.h \
		/usr/local/qwt-6.1.0/src/qwt_global.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_text.h \
		/usr/local/qwt-6.1.0/src/qwt_event_pattern.h \
		plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_date.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_div.h \
		/usr/local/qwt-6.1.0/src/qwt_interval.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_dict.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_item.h \
		/usr/local/qwt-6.1.0/src/qwt_legend_data.h \
		/usr/local/qwt-6.1.0/src/qwt_graphic.h \
		/usr/local/qwt-6.1.0/src/qwt_null_paintdevice.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_map.h \
		/usr/local/qwt-6.1.0/src/qwt_transform.h \
		CheckpointMessages.h \
		VideoFrame.h \
		db_VideoFrame.h \
		LoginPassword.h \
		LoginDialog.h \
		ModelLoginPassword.h \
		TableEditDialog.h \
		ModelVisualParam.h \
		CheckPointEditDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_curve.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_seriesitem.h \
		/usr/local/qwt-6.1.0/src/qwt_series_data.h \
		/usr/local/qwt-6.1.0/src/qwt_samples.h \
		/usr/local/qwt-6.1.0/src/qwt_point_3d.h \
		/usr/local/qwt-6.1.0/src/qwt_point_polar.h \
		/usr/local/qwt-6.1.0/src/qwt_math.h \
		/usr/local/qwt-6.1.0/src/qwt_series_store.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_grid.h \
		/usr/local/qwt-6.1.0/src/qwt_symbol.h \
		/usr/local/qwt-6.1.0/src/qwt_legend.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_legend.h \
		ModelArchivSignal.h \
		DelegatArchivSignal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DbLoginPasswords.o DbLoginPasswords.cpp

LoginDialog.o: LoginDialog.cpp LoginDialog.h \
		AllHeaders.h \
		dbconn.h \
		db_VisualParam.h \
		VisualParam.h \
		Signal.h \
		db_signal.h \
		vec_signal.h \
		CheckPointProperties.h \
		db_CheckPointProperties.h \
		CheckpointPropDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_zoomer.h \
		/usr/local/qwt-6.1.0/src/qwt_global.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_text.h \
		/usr/local/qwt-6.1.0/src/qwt_event_pattern.h \
		plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_date.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_div.h \
		/usr/local/qwt-6.1.0/src/qwt_interval.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_dict.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_item.h \
		/usr/local/qwt-6.1.0/src/qwt_legend_data.h \
		/usr/local/qwt-6.1.0/src/qwt_graphic.h \
		/usr/local/qwt-6.1.0/src/qwt_null_paintdevice.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_map.h \
		/usr/local/qwt-6.1.0/src/qwt_transform.h \
		CheckpointMessages.h \
		VideoFrame.h \
		db_VideoFrame.h \
		LoginPassword.h \
		DbLoginPasswords.h \
		ModelLoginPassword.h \
		TableEditDialog.h \
		ModelVisualParam.h \
		CheckPointEditDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_curve.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_seriesitem.h \
		/usr/local/qwt-6.1.0/src/qwt_series_data.h \
		/usr/local/qwt-6.1.0/src/qwt_samples.h \
		/usr/local/qwt-6.1.0/src/qwt_point_3d.h \
		/usr/local/qwt-6.1.0/src/qwt_point_polar.h \
		/usr/local/qwt-6.1.0/src/qwt_math.h \
		/usr/local/qwt-6.1.0/src/qwt_series_store.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_grid.h \
		/usr/local/qwt-6.1.0/src/qwt_symbol.h \
		/usr/local/qwt-6.1.0/src/qwt_legend.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_legend.h \
		ModelArchivSignal.h \
		DelegatArchivSignal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o LoginDialog.o LoginDialog.cpp

ModelLoginPassword.o: ModelLoginPassword.cpp ModelLoginPassword.h \
		AllHeaders.h \
		dbconn.h \
		db_VisualParam.h \
		VisualParam.h \
		Signal.h \
		db_signal.h \
		vec_signal.h \
		CheckPointProperties.h \
		db_CheckPointProperties.h \
		CheckpointPropDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_zoomer.h \
		/usr/local/qwt-6.1.0/src/qwt_global.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_text.h \
		/usr/local/qwt-6.1.0/src/qwt_event_pattern.h \
		plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_date.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_div.h \
		/usr/local/qwt-6.1.0/src/qwt_interval.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_dict.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_item.h \
		/usr/local/qwt-6.1.0/src/qwt_legend_data.h \
		/usr/local/qwt-6.1.0/src/qwt_graphic.h \
		/usr/local/qwt-6.1.0/src/qwt_null_paintdevice.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_map.h \
		/usr/local/qwt-6.1.0/src/qwt_transform.h \
		CheckpointMessages.h \
		VideoFrame.h \
		db_VideoFrame.h \
		LoginPassword.h \
		DbLoginPasswords.h \
		LoginDialog.h \
		TableEditDialog.h \
		ModelVisualParam.h \
		CheckPointEditDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_curve.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_seriesitem.h \
		/usr/local/qwt-6.1.0/src/qwt_series_data.h \
		/usr/local/qwt-6.1.0/src/qwt_samples.h \
		/usr/local/qwt-6.1.0/src/qwt_point_3d.h \
		/usr/local/qwt-6.1.0/src/qwt_point_polar.h \
		/usr/local/qwt-6.1.0/src/qwt_math.h \
		/usr/local/qwt-6.1.0/src/qwt_series_store.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_grid.h \
		/usr/local/qwt-6.1.0/src/qwt_symbol.h \
		/usr/local/qwt-6.1.0/src/qwt_legend.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_legend.h \
		ModelArchivSignal.h \
		DelegatArchivSignal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ModelLoginPassword.o ModelLoginPassword.cpp

TableEditDialog.o: TableEditDialog.cpp TableEditDialog.h \
		AllHeaders.h \
		dbconn.h \
		db_VisualParam.h \
		VisualParam.h \
		Signal.h \
		db_signal.h \
		vec_signal.h \
		CheckPointProperties.h \
		db_CheckPointProperties.h \
		CheckpointPropDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_zoomer.h \
		/usr/local/qwt-6.1.0/src/qwt_global.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_text.h \
		/usr/local/qwt-6.1.0/src/qwt_event_pattern.h \
		plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_date.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_div.h \
		/usr/local/qwt-6.1.0/src/qwt_interval.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_dict.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_item.h \
		/usr/local/qwt-6.1.0/src/qwt_legend_data.h \
		/usr/local/qwt-6.1.0/src/qwt_graphic.h \
		/usr/local/qwt-6.1.0/src/qwt_null_paintdevice.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_map.h \
		/usr/local/qwt-6.1.0/src/qwt_transform.h \
		CheckpointMessages.h \
		VideoFrame.h \
		db_VideoFrame.h \
		LoginPassword.h \
		DbLoginPasswords.h \
		LoginDialog.h \
		ModelLoginPassword.h \
		ModelVisualParam.h \
		CheckPointEditDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_curve.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_seriesitem.h \
		/usr/local/qwt-6.1.0/src/qwt_series_data.h \
		/usr/local/qwt-6.1.0/src/qwt_samples.h \
		/usr/local/qwt-6.1.0/src/qwt_point_3d.h \
		/usr/local/qwt-6.1.0/src/qwt_point_polar.h \
		/usr/local/qwt-6.1.0/src/qwt_math.h \
		/usr/local/qwt-6.1.0/src/qwt_series_store.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_grid.h \
		/usr/local/qwt-6.1.0/src/qwt_symbol.h \
		/usr/local/qwt-6.1.0/src/qwt_legend.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_legend.h \
		ModelArchivSignal.h \
		DelegatArchivSignal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TableEditDialog.o TableEditDialog.cpp

ModelVisualParam.o: ModelVisualParam.cpp ModelVisualParam.h \
		AllHeaders.h \
		dbconn.h \
		db_VisualParam.h \
		VisualParam.h \
		Signal.h \
		db_signal.h \
		vec_signal.h \
		CheckPointProperties.h \
		db_CheckPointProperties.h \
		CheckpointPropDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_zoomer.h \
		/usr/local/qwt-6.1.0/src/qwt_global.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_text.h \
		/usr/local/qwt-6.1.0/src/qwt_event_pattern.h \
		plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_date.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_div.h \
		/usr/local/qwt-6.1.0/src/qwt_interval.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_dict.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_item.h \
		/usr/local/qwt-6.1.0/src/qwt_legend_data.h \
		/usr/local/qwt-6.1.0/src/qwt_graphic.h \
		/usr/local/qwt-6.1.0/src/qwt_null_paintdevice.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_map.h \
		/usr/local/qwt-6.1.0/src/qwt_transform.h \
		CheckpointMessages.h \
		VideoFrame.h \
		db_VideoFrame.h \
		LoginPassword.h \
		DbLoginPasswords.h \
		LoginDialog.h \
		ModelLoginPassword.h \
		TableEditDialog.h \
		CheckPointEditDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_curve.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_seriesitem.h \
		/usr/local/qwt-6.1.0/src/qwt_series_data.h \
		/usr/local/qwt-6.1.0/src/qwt_samples.h \
		/usr/local/qwt-6.1.0/src/qwt_point_3d.h \
		/usr/local/qwt-6.1.0/src/qwt_point_polar.h \
		/usr/local/qwt-6.1.0/src/qwt_math.h \
		/usr/local/qwt-6.1.0/src/qwt_series_store.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_grid.h \
		/usr/local/qwt-6.1.0/src/qwt_symbol.h \
		/usr/local/qwt-6.1.0/src/qwt_legend.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_legend.h \
		ModelArchivSignal.h \
		DelegatArchivSignal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ModelVisualParam.o ModelVisualParam.cpp

CheckPointEditDialog.o: CheckPointEditDialog.cpp CheckPointEditDialog.h \
		AllHeaders.h \
		dbconn.h \
		db_VisualParam.h \
		VisualParam.h \
		Signal.h \
		db_signal.h \
		vec_signal.h \
		CheckPointProperties.h \
		db_CheckPointProperties.h \
		CheckpointPropDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_zoomer.h \
		/usr/local/qwt-6.1.0/src/qwt_global.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_text.h \
		/usr/local/qwt-6.1.0/src/qwt_event_pattern.h \
		plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_date.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_div.h \
		/usr/local/qwt-6.1.0/src/qwt_interval.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_dict.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_item.h \
		/usr/local/qwt-6.1.0/src/qwt_legend_data.h \
		/usr/local/qwt-6.1.0/src/qwt_graphic.h \
		/usr/local/qwt-6.1.0/src/qwt_null_paintdevice.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_map.h \
		/usr/local/qwt-6.1.0/src/qwt_transform.h \
		CheckpointMessages.h \
		VideoFrame.h \
		db_VideoFrame.h \
		LoginPassword.h \
		DbLoginPasswords.h \
		LoginDialog.h \
		ModelLoginPassword.h \
		TableEditDialog.h \
		ModelVisualParam.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_curve.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_seriesitem.h \
		/usr/local/qwt-6.1.0/src/qwt_series_data.h \
		/usr/local/qwt-6.1.0/src/qwt_samples.h \
		/usr/local/qwt-6.1.0/src/qwt_point_3d.h \
		/usr/local/qwt-6.1.0/src/qwt_point_polar.h \
		/usr/local/qwt-6.1.0/src/qwt_math.h \
		/usr/local/qwt-6.1.0/src/qwt_series_store.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_grid.h \
		/usr/local/qwt-6.1.0/src/qwt_symbol.h \
		/usr/local/qwt-6.1.0/src/qwt_legend.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_legend.h \
		ModelArchivSignal.h \
		DelegatArchivSignal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CheckPointEditDialog.o CheckPointEditDialog.cpp

CheckpointPropDialog.o: CheckpointPropDialog.cpp CheckpointPropDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_zoomer.h \
		/usr/local/qwt-6.1.0/src/qwt_global.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_text.h \
		/usr/local/qwt-6.1.0/src/qwt_event_pattern.h \
		AllHeaders.h \
		dbconn.h \
		db_VisualParam.h \
		VisualParam.h \
		Signal.h \
		db_signal.h \
		vec_signal.h \
		CheckPointProperties.h \
		db_CheckPointProperties.h \
		CheckpointMessages.h \
		VideoFrame.h \
		db_VideoFrame.h \
		LoginPassword.h \
		DbLoginPasswords.h \
		LoginDialog.h \
		ModelLoginPassword.h \
		TableEditDialog.h \
		ModelVisualParam.h \
		CheckPointEditDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_dict.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_item.h \
		/usr/local/qwt-6.1.0/src/qwt_legend_data.h \
		/usr/local/qwt-6.1.0/src/qwt_graphic.h \
		/usr/local/qwt-6.1.0/src/qwt_null_paintdevice.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_map.h \
		/usr/local/qwt-6.1.0/src/qwt_transform.h \
		/usr/local/qwt-6.1.0/src/qwt_interval.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_curve.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_seriesitem.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_div.h \
		/usr/local/qwt-6.1.0/src/qwt_series_data.h \
		/usr/local/qwt-6.1.0/src/qwt_samples.h \
		/usr/local/qwt-6.1.0/src/qwt_point_3d.h \
		/usr/local/qwt-6.1.0/src/qwt_point_polar.h \
		/usr/local/qwt-6.1.0/src/qwt_math.h \
		/usr/local/qwt-6.1.0/src/qwt_series_store.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_grid.h \
		/usr/local/qwt-6.1.0/src/qwt_symbol.h \
		/usr/local/qwt-6.1.0/src/qwt_legend.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_legend.h \
		plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_date.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_scale_draw.h \
		ModelArchivSignal.h \
		DelegatArchivSignal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CheckpointPropDialog.o CheckpointPropDialog.cpp

plot.o: plot.cpp plot.h \
		AllHeaders.h \
		dbconn.h \
		db_VisualParam.h \
		VisualParam.h \
		Signal.h \
		db_signal.h \
		vec_signal.h \
		CheckPointProperties.h \
		db_CheckPointProperties.h \
		CheckpointPropDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_zoomer.h \
		/usr/local/qwt-6.1.0/src/qwt_global.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_text.h \
		/usr/local/qwt-6.1.0/src/qwt_event_pattern.h \
		CheckpointMessages.h \
		VideoFrame.h \
		db_VideoFrame.h \
		LoginPassword.h \
		DbLoginPasswords.h \
		LoginDialog.h \
		ModelLoginPassword.h \
		TableEditDialog.h \
		ModelVisualParam.h \
		CheckPointEditDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_dict.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_item.h \
		/usr/local/qwt-6.1.0/src/qwt_legend_data.h \
		/usr/local/qwt-6.1.0/src/qwt_graphic.h \
		/usr/local/qwt-6.1.0/src/qwt_null_paintdevice.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_map.h \
		/usr/local/qwt-6.1.0/src/qwt_transform.h \
		/usr/local/qwt-6.1.0/src/qwt_interval.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_curve.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_seriesitem.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_div.h \
		/usr/local/qwt-6.1.0/src/qwt_series_data.h \
		/usr/local/qwt-6.1.0/src/qwt_samples.h \
		/usr/local/qwt-6.1.0/src/qwt_point_3d.h \
		/usr/local/qwt-6.1.0/src/qwt_point_polar.h \
		/usr/local/qwt-6.1.0/src/qwt_math.h \
		/usr/local/qwt-6.1.0/src/qwt_series_store.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_grid.h \
		/usr/local/qwt-6.1.0/src/qwt_symbol.h \
		/usr/local/qwt-6.1.0/src/qwt_legend.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_legend.h \
		ModelArchivSignal.h \
		DelegatArchivSignal.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_date.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_scale_draw.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o plot.o plot.cpp

Signal.o: Signal.cpp Signal.h \
		AllHeaders.h \
		dbconn.h \
		db_VisualParam.h \
		VisualParam.h \
		db_signal.h \
		vec_signal.h \
		CheckPointProperties.h \
		db_CheckPointProperties.h \
		CheckpointPropDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_zoomer.h \
		/usr/local/qwt-6.1.0/src/qwt_global.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_text.h \
		/usr/local/qwt-6.1.0/src/qwt_event_pattern.h \
		plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_date.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_div.h \
		/usr/local/qwt-6.1.0/src/qwt_interval.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_dict.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_item.h \
		/usr/local/qwt-6.1.0/src/qwt_legend_data.h \
		/usr/local/qwt-6.1.0/src/qwt_graphic.h \
		/usr/local/qwt-6.1.0/src/qwt_null_paintdevice.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_map.h \
		/usr/local/qwt-6.1.0/src/qwt_transform.h \
		CheckpointMessages.h \
		VideoFrame.h \
		db_VideoFrame.h \
		LoginPassword.h \
		DbLoginPasswords.h \
		LoginDialog.h \
		ModelLoginPassword.h \
		TableEditDialog.h \
		ModelVisualParam.h \
		CheckPointEditDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_curve.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_seriesitem.h \
		/usr/local/qwt-6.1.0/src/qwt_series_data.h \
		/usr/local/qwt-6.1.0/src/qwt_samples.h \
		/usr/local/qwt-6.1.0/src/qwt_point_3d.h \
		/usr/local/qwt-6.1.0/src/qwt_point_polar.h \
		/usr/local/qwt-6.1.0/src/qwt_math.h \
		/usr/local/qwt-6.1.0/src/qwt_series_store.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_grid.h \
		/usr/local/qwt-6.1.0/src/qwt_symbol.h \
		/usr/local/qwt-6.1.0/src/qwt_legend.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_legend.h \
		ModelArchivSignal.h \
		DelegatArchivSignal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Signal.o Signal.cpp

ModelArchivSignal.o: ModelArchivSignal.cpp ModelArchivSignal.h \
		AllHeaders.h \
		dbconn.h \
		db_VisualParam.h \
		VisualParam.h \
		Signal.h \
		db_signal.h \
		vec_signal.h \
		CheckPointProperties.h \
		db_CheckPointProperties.h \
		CheckpointPropDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_zoomer.h \
		/usr/local/qwt-6.1.0/src/qwt_global.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_text.h \
		/usr/local/qwt-6.1.0/src/qwt_event_pattern.h \
		plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_date.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_div.h \
		/usr/local/qwt-6.1.0/src/qwt_interval.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_dict.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_item.h \
		/usr/local/qwt-6.1.0/src/qwt_legend_data.h \
		/usr/local/qwt-6.1.0/src/qwt_graphic.h \
		/usr/local/qwt-6.1.0/src/qwt_null_paintdevice.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_map.h \
		/usr/local/qwt-6.1.0/src/qwt_transform.h \
		CheckpointMessages.h \
		VideoFrame.h \
		db_VideoFrame.h \
		LoginPassword.h \
		DbLoginPasswords.h \
		LoginDialog.h \
		ModelLoginPassword.h \
		TableEditDialog.h \
		ModelVisualParam.h \
		CheckPointEditDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_curve.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_seriesitem.h \
		/usr/local/qwt-6.1.0/src/qwt_series_data.h \
		/usr/local/qwt-6.1.0/src/qwt_samples.h \
		/usr/local/qwt-6.1.0/src/qwt_point_3d.h \
		/usr/local/qwt-6.1.0/src/qwt_point_polar.h \
		/usr/local/qwt-6.1.0/src/qwt_math.h \
		/usr/local/qwt-6.1.0/src/qwt_series_store.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_grid.h \
		/usr/local/qwt-6.1.0/src/qwt_symbol.h \
		/usr/local/qwt-6.1.0/src/qwt_legend.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_legend.h \
		DelegatArchivSignal.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ModelArchivSignal.o ModelArchivSignal.cpp

DelegatArchivSignal.o: DelegatArchivSignal.cpp DelegatArchivSignal.h \
		ModelArchivSignal.h \
		AllHeaders.h \
		dbconn.h \
		db_VisualParam.h \
		VisualParam.h \
		Signal.h \
		db_signal.h \
		vec_signal.h \
		CheckPointProperties.h \
		db_CheckPointProperties.h \
		CheckpointPropDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_zoomer.h \
		/usr/local/qwt-6.1.0/src/qwt_global.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_picker.h \
		/usr/local/qwt-6.1.0/src/qwt_text.h \
		/usr/local/qwt-6.1.0/src/qwt_event_pattern.h \
		plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_panner.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_date.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_engine.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_div.h \
		/usr/local/qwt-6.1.0/src/qwt_interval.h \
		/usr/local/qwt-6.1.0/src/qwt_date_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_scale_draw.h \
		/usr/local/qwt-6.1.0/src/qwt_plot.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_dict.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_item.h \
		/usr/local/qwt-6.1.0/src/qwt_legend_data.h \
		/usr/local/qwt-6.1.0/src/qwt_graphic.h \
		/usr/local/qwt-6.1.0/src/qwt_null_paintdevice.h \
		/usr/local/qwt-6.1.0/src/qwt_scale_map.h \
		/usr/local/qwt-6.1.0/src/qwt_transform.h \
		CheckpointMessages.h \
		VideoFrame.h \
		db_VideoFrame.h \
		LoginPassword.h \
		DbLoginPasswords.h \
		LoginDialog.h \
		ModelLoginPassword.h \
		TableEditDialog.h \
		ModelVisualParam.h \
		CheckPointEditDialog.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_curve.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_seriesitem.h \
		/usr/local/qwt-6.1.0/src/qwt_series_data.h \
		/usr/local/qwt-6.1.0/src/qwt_samples.h \
		/usr/local/qwt-6.1.0/src/qwt_point_3d.h \
		/usr/local/qwt-6.1.0/src/qwt_point_polar.h \
		/usr/local/qwt-6.1.0/src/qwt_math.h \
		/usr/local/qwt-6.1.0/src/qwt_series_store.h \
		/usr/local/qwt-6.1.0/src/qwt_plot_grid.h \
		/usr/local/qwt-6.1.0/src/qwt_symbol.h \
		/usr/local/qwt-6.1.0/src/qwt_legend.h \
		/usr/local/qwt-6.1.0/src/qwt_abstract_legend.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o DelegatArchivSignal.o DelegatArchivSignal.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_PromengDialog.o: moc_PromengDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_PromengDialog.o moc_PromengDialog.cpp

moc_bitmapworker.o: moc_bitmapworker.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_bitmapworker.o moc_bitmapworker.cpp

moc_db_signal.o: moc_db_signal.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_db_signal.o moc_db_signal.cpp

moc_LoginDialog.o: moc_LoginDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_LoginDialog.o moc_LoginDialog.cpp

moc_ModelLoginPassword.o: moc_ModelLoginPassword.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ModelLoginPassword.o moc_ModelLoginPassword.cpp

moc_TableEditDialog.o: moc_TableEditDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_TableEditDialog.o moc_TableEditDialog.cpp

moc_ModelVisualParam.o: moc_ModelVisualParam.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ModelVisualParam.o moc_ModelVisualParam.cpp

moc_CheckPointEditDialog.o: moc_CheckPointEditDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_CheckPointEditDialog.o moc_CheckPointEditDialog.cpp

moc_CheckpointPropDialog.o: moc_CheckpointPropDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_CheckpointPropDialog.o moc_CheckpointPropDialog.cpp

moc_plot.o: moc_plot.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_plot.o moc_plot.cpp

moc_ModelArchivSignal.o: moc_ModelArchivSignal.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ModelArchivSignal.o moc_ModelArchivSignal.cpp

moc_DelegatArchivSignal.o: moc_DelegatArchivSignal.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_DelegatArchivSignal.o moc_DelegatArchivSignal.cpp

qrc_application.o: qrc_application.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_application.o qrc_application.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

