--------------------------------------------------------
--  DDL for Table RM_VISUAL_PARAM
--------------------------------------------------------

  CREATE TABLE "ASKRO"."RM_VISUAL_PARAM" 
   (	"GUID" NUMBER, 
	"GUID_RM_PARAM" NUMBER, 
	"GUID_PLAN_TREE" NUMBER, 
	"TOP_STATE" NUMBER DEFAULT 10, 
	"LEFT_STATE" NUMBER DEFAULT 10, 
	"DISPLAY_TYPE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MDATA" ;
 

   COMMENT ON COLUMN "ASKRO"."RM_VISUAL_PARAM"."GUID" IS 'Global ID';
 
   COMMENT ON COLUMN "ASKRO"."RM_VISUAL_PARAM"."GUID_RM_PARAM" IS 'Parameter ID';
 
   COMMENT ON COLUMN "ASKRO"."RM_VISUAL_PARAM"."GUID_PLAN_TREE" IS 'Plan ID';
 
   COMMENT ON COLUMN "ASKRO"."RM_VISUAL_PARAM"."TOP_STATE" IS 'Top state';
 
   COMMENT ON COLUMN "ASKRO"."RM_VISUAL_PARAM"."LEFT_STATE" IS 'Left state';
 
   COMMENT ON COLUMN "ASKRO"."RM_VISUAL_PARAM"."DISPLAY_TYPE" IS 'Display type (0 - is parameter, Other - is status (no of pictures))';
 
   COMMENT ON TABLE "ASKRO"."RM_VISUAL_PARAM"  IS 'Visual param in plan';
